FROM ubuntu:20.04

ENV PYTHONDONTWRITEBYTECODE=true \
    PATH=/opt/conda/bin:$PATH

RUN set -ex && \
    mkdir -p /etc/ssl/certs/java && \
    apt-get -y -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq install -y \
        wget \
        curl \
    && \
    # Cleanup
    rm -rf /var/lib/apt/lists/* && \
    apt-get -qq autoclean && \
    apt-get -qq clean && \
    rm -rf /var/cache/* /tmp/*

# Install conda to manage python and R packages
ARG miniconda_version="py37_4.9.2"
ARG miniconda_flavor="Linux-x86_64"
#ARG miniconda_flavor="MacOSX-arm64"
# Hashes via https://docs.conda.io/en/latest/miniconda_hashes.html
ARG miniconda_sha256="79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31"

RUN set -ex && \
    wget -nv https://repo.anaconda.com/miniconda/Miniconda3-${miniconda_version}-${miniconda_flavor}.sh -O miniconda.sh && \
    echo "${miniconda_sha256} miniconda.sh" > anaconda.sha256 && \
    sha256sum --strict -c anaconda.sha256 && \
    bash miniconda.sh -b -p /opt/conda

RUN set -ex && \
    conda config --set always_yes yes --set changeps1 no && \
    conda info -a && \
    conda install --quiet --freeze-installed -c conda-forge mamba && \
    conda install --quiet --freeze-installed -c main conda-pack

ADD packer.sh /packer.sh

ENTRYPOINT [ "/packer.sh" ]
