version: "2"

services:

  spark:
    image: ghcr.io/datatok/spark:v3.2.1-1
    volumes:
    - ./spark_datatok:/opt/spark_docker
    command:
    - cp -r /opt/spark /opt/spark_docker

  server:
    build: 
      context: ../src/server
      args:
        zeppelin_version: 0.10.1
    ports:
    - 8080:8080

  int:
    build: 
      context: ../src/interpreter
      args:
        zeppelin_version: 0.10.1
    command:
    - /opt/zeppelin/bin/interpreter.sh
    - '-d'
    - /opt/zeppelin/interpreter/spark
    - '-r'
    - '12321:12321'
    - '-c'
    - zep
    - '-p'
    - '38853'
    - '-i'
    - spark-shared_process
    - '-l'
    - /tmp/local-repo/spark
    - '-g'
    - spark
    ports:
    - 4041:4040
    volumes:
    - ./spark_datatok:/opt/spark
    environment:
      SPARK_HOME: /opt/spark
      ZEPPELIN_HOME: /opt/zeppelin
