version: "2"

services:

  docker:
    image: bobrik/socat
    command: "TCP-LISTEN:1234,fork UNIX-CONNECT:/var/run/docker.sock"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - 1234:1234

  spark:
    image: ghcr.io/datatok/spark:v3.2.1-1
    volumes:
    - ./spark_datatok:/opt/spark_docker
    command:
    - cp -r /opt/spark /opt/spark_docker

  server:
    #image: ghcr.io/datatok/zeppelin-server:0.10.1-edge
    build: 
      context: ../src/server
      args:
        zeppelin_version: 0.10.1
    environment:
      #ZEPPELIN_IN_DOCKER: "true"
      #ZEPPELIN_RUN_MODE: docker
      DOCKER_HOST: http://docker:1234
      ZEPPELIN_DOCKER_CONTAINER_IMAGE: dev_int-r
      ZEPPELIN_INTERPRETER_CONNECT_TIMEOUT: 12000000
      ZEPPELIN_SERVER_RPC_PORTRANGE: "33800:33801"
      ZEPPELIN_INTERPRETER_RPC_PORTRANGE: "12321:12321"
    volumes:
    - notebook:/opt/zeppelin/notebook
    ports:
    - 8080:8080

  int:
    #image: ghcr.io/datatok/zeppelin-interpreter:0.10.1-edge
    hostname: int-${ZEP_INT}
    build:
      context: ../src/interpreter-r-full
      args:
        zeppelin_version: 0.10.1
    command:
    - /bin/sh
    - -c
    - |
        set -ex

        /opt/zeppelin/bin/interpreter.sh \
        -d /opt/zeppelin/interpreter/${ZEP_INT} \
        -r '12321:12321' \
        -c server \
        -p 33800 \
        -i r-shared_process \
        -l /tmp/local-repo/spark \
        -g ${ZEP_INT}
    ports:
    - 4041:4040
    - 8081:8080
    volumes:
    #- ./conda_packs:/opt/conda/packs:ro
    - ./spark-3.3.0:/opt/spark
    #- ../../../ebuildy/zeppelin/zeppelin-distribution/target/zeppelin-0.11.0-SNAPSHOT/zeppelin-0.11.0-SNAPSHOT/interpreter:/opt/zeppelin/interpreter
    - ./interpreter.sh:/opt/zeppelin/bin/interpreter.sh:ro
    environment:
      SPARK_HOME: /opt/spark
      ZEPPELIN_HOME: /opt/zeppelin
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-arm64
      ZEP_INT: ${ZEP_INT}

  r-packer:
    build:
      context: ../src/r-packer
    command: /opt/conda/python_3_with_R.yaml /opt/conda/packs/python_3_with_R.tar.gz
    volumes:
    - ./python_3_with_R.yaml:/opt/conda/python_3_with_R.yaml:ro
    - ./conda_packs:/opt/conda/packs:rw

volumes:
  notebook: {}