name: Continuous integration

on:
  push:
    branches:
      - main
      - ci
      - dev
    tags:
      - 'v*'

jobs:

  docker-build:
    name: Package app as Docker image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - flavor: server
          zeppelin_version: 0.10.1
        - flavor: interpreter-spark
          zeppelin_version: 0.10.1
        - flavor: interpreter-r
          zeppelin_version: 0.10.1
    
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: datatok/zeppelin-${{ matrix.flavor }}

    steps:

      -
        name: Checkout
        uses: actions/checkout@v2
    
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          driver-opts: image=moby/buildkit:v0.9.1

      -
        name: Login to Github registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=edge,prefix=${{ matrix.zeppelin_version }}-,branch=main
            type=ref,enable=true,prefix=-${{ matrix.zeppelin_version }}-,event=tag
            type=edge,prefix=${{ matrix.zeppelin_version }}-,branch=dev

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: src/${{ matrix.flavor }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            zeppelin_version=${{ matrix.zeppelin_version }}